@startuml
title 要件定義図

actor オーナー
actor 利用者
rectangle システム境界 {
boundary ログイン画面
boundary 登録画面
boundary 会議室一覧画面
boundary 会議室詳細画面
usecase 登録する
usecase ログインする
usecase 会議室を登録する
usecase 会議室を検索する
usecase 会議室を予約する
rectangle システム {
    node レンタル会議室 {
        node 収容人数
        node 貸出可能期間
    }
    node 予約内容 {
        node 貸出期間
    }
}
ログインする -- システム
会議室を登録する -- システム
会議室を検索する -- システム
会議室を予約する -- システム
}
利用者 -- 登録画面
登録画面 -- 登録する
利用者 -- ログイン画面
ログイン画面 -- ログインする
利用者 -- 会議室一覧画面
会議室一覧画面 -- 会議室を検索する
利用者 -- 会議室詳細画面
会議室詳細画面 -- 会議室を予約する
オーナー -- 会議室一覧画面
会議室一覧画面 -- 会議室を登録する
@enduml