@startuml
title 利用者会議室を検索する

note as N1
基本コース:
利用者は会議室一覧画面に遷移する。
事前にログインを終えていなければならない。
利用者は検索条件を入力して検索を実行する。
システムは検索条件に合うを会議室を取得する。
システムは取得した会議室を会議室一覧画面に表示する。
利用者は表示された会議室を選択する。
システムは会議室詳細画面へ遷移する。
代替コース:
条件に合う会議室が一つもない: 空の表を表示する。
end note

actor 利用者
boundary 会議室一覧画面
usecase ログインする
entity 会議室
control 会議室を検索する
control 住所で検索する
control 日時で検索する
control 会議室を選択する
control "条件に合う会議室は存在するか？" as a
control 空の表を返す #grey
boundary 会議室詳細画面
利用者 -- 会議室一覧画面
会議室一覧画面 -- 会議室を検索する
会議室一覧画面 --> 会議室を選択する
会議室を選択する --> 会議室詳細画面
会議室一覧画面 <-- ログインする : <<precedes>>
住所で検索する <-- 会議室を検索する : <<invokes>>
日時で検索する <-- 会議室を検索する : <<invokes>>
会議室を検索する -- a
a --> 会議室 : yes
a --> 空の表を返す : no
@enduml