@startuml
title 利用者会議室を予約する

note as N1
基本コース:
利用者は会議室詳細画面に遷移する。
事前にログインを終えていなければならない。
利用者は貸与期間を入力する。
利用者は会議室を予約する。
システムは予約可能か判断する。
システムは予約可能の場合、予約終了画面へ遷移する。
代替コース:
予約不可能の場合: 予約不可能な理由を画面に表示する。
end note

actor 利用者
boundary 会議室詳細画面
boundary 会議一覧画面
usecase ログインする
entity プラン
entity 会議室
entity 予約内容
entity "利用者" as b
control 貸与期間を入力する
control プランを選択する
control 会議室を予約する
control "予約可能か？" as a
control "予約受付日以降か？" as c
control "貸与可能期間内か？" as d
control "既に予約を取られていないか？" as e
control 予約不可能な理由を返す #grey
control 予約内容を保存する
利用者 -- 会議室詳細画面
会議室詳細画面 <-- ログインする : <<precedes>>
会議室詳細画面 -- 貸与期間を入力する
会議室詳細画面 -- プランを選択する
会議室詳細画面 -- 会議室を予約する
会議室を予約する --> a
会議室を予約する -- 会議室
会議室を予約する -- 予約内容
会議室を予約する -- プラン
会議室を予約する -- b
a --> c : yes
a --> 予約不可能な理由を返す : no
c --> d : yes
c --> 予約不可能な理由を返す : no
d --> e : yes
d --> 予約不可能な理由を返す : no
e --> 予約内容を保存する : yes
e --> 予約不可能な理由を返す : no
予約内容を保存する --> 会議一覧画面
予約内容を保存する --> 予約不可能な理由を返す : no
予約不可能な理由を返す --> 会議室詳細画面
@enduml