@startuml
title クラス図

skinparam class {
BackgroundColor<<集約>> LightSkyBlue
FontColor<<集約>> Red
FontSize<<集約>> 18
}

class 会議室 <<集約>> {
-会議室ID: 会議室ID
-会議室名: 会議室名
-収容人数: 収容人数
-貸与可能期間一覧: List<貸与可能期間>
-料金単価: 料金
-住所: 住所
}
class 会議室ID <<VO>>
会議室 o-- 会議室ID
class 会議室名 <<VO>>
会議室 o-- 会議室名
class 収容人数 <<VO>> 
会議室 o-- 収容人数
class 料金 <<VO>>
会議室 o-- 料金
class 住所 <<VO>>
会議室 o-- 住所

class 貸与可能期間 <<VO>> {
-貸与可能時間自: 貸与可能時間自
-貸与可能時間至: 貸与可能時間至
}
class 貸与可能時間自 <<VO>>
class 貸与可能時間至 <<VO>>
貸与可能期間 o-- 貸与可能時間自
貸与可能期間 o-- 貸与可能時間至
会議室 o-- 貸与可能期間

class 利用者 <<集約>> {
-利用者ID: 利用者ID
-利用者名: 利用者名
}
class 利用者ID <<VO>>
利用者 o-- 利用者ID
class 利用者名 <<VO>>
利用者 o-- 利用者名


class 予約内容 <<集約>> {
-予約内容ID: 予約内容ID
-会議室ID: 会議室ID
-利用者ID: 利用者ID
-貸与期間: 貸与期間
-料金単価: 料金
+合計料金算出(): 料金
}
class 予約内容ID <<VO>>
予約内容 o-- 予約内容ID
予約内容 o-- 会議室ID
予約内容 o-- 利用者ID
予約内容 o-- 料金

class 貸与期間 <<VO>> {
-貸与時間自: 貸与時間自
-貸与時間至: 貸与時間至
}
class 貸与時間自 <<VO>>
class 貸与時間至 <<VO>>
貸与期間 o-- 貸与時間自
貸与期間 o-- 貸与時間至
予約内容 o-- 貸与期間
@enduml